<a href="https://colab.research.google.com/github/Ahmed-Ashraf-Marzouk/data-mining-heart-attack/blob/main/K_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#imports 

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import matplotlib.pyplot as plt
import seaborn as sns
# from kneed import KneeLocator
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score


In [2]:
!gdown "1uDSWhhUBPFjjUJmsh4-FLiRM2AakrC8f"
!unrar x "./dataset.rar" -idq

Downloading...
From: https://drive.google.com/uc?id=1uDSWhhUBPFjjUJmsh4-FLiRM2AakrC8f
To: /content/dataset.rar
100% 3.82k/3.82k [00:00<00:00, 4.95MB/s]


In [12]:
col_names = ['Age','Gender','CP', 'Trtbps', 'Chol', 'FBS', 'Rest_ecg', 'Thalach', 'Exang', 'Old_peak', 'Slope', 'CA', 'Thall', 'Output']
df = pd.read_csv('dataset/heart.csv', header = 0, names = col_names)
rearranged_col_names = ['Age', 'Gender', 'Exang', 'CA', 'CP', 'Trtbps', 'Chol', 'FBS', 'Rest_ecg', 'Thalach', 'Old_peak', 'Slope','Thall', 'Output']
df = df[rearranged_col_names]
df.head()

Age  Gender  Exang  CA  CP  Trtbps  Chol  FBS  Rest_ecg  Thalach  Old_peak  \
0   63       1      0   0   3     145   233    1         0      150       2.3   
1   37       1      0   0   2     130   250    0         1      187       3.5   
2   41       0      0   0   1     130   204    0         0      172       1.4   
3   56       1      0   0   1     120   236    0         1      178       0.8   
4   57       0      1   0   0     120   354    0         1      163       0.6   

   Slope  Thall  Output  
0      0      1       1  
1      0      2       1  
2      2      2       1  
3      2      2       1  
4      2      2       1

In [13]:
y = df['Output']
df.drop(['Output'], axis = 1, inplace = True) 
#standardization
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df)
scaled_features

array([[ 0.9521966 ,  0.68100522, -0.69663055, ...,  1.08733806,
        -2.27457861, -2.14887271],
       [-1.91531289,  0.68100522, -0.69663055, ...,  2.12257273,
        -2.27457861, -0.51292188],
       [-1.47415758, -1.46841752, -0.69663055, ...,  0.31091206,
         0.97635214, -0.51292188],
       ...,
       [ 1.50364073,  0.68100522, -0.69663055, ...,  2.03630317,
        -0.64911323,  1.12302895],
       [ 0.29046364,  0.68100522,  1.43548113, ...,  0.13837295,
        -0.64911323,  1.12302895],
       [ 0.29046364, -1.46841752, -0.69663055, ..., -0.89686172,
        -0.64911323, -0.51292188]])

In [20]:
kmeans = KMeans(init="random", n_clusters= 2, n_init=10, max_iter=300, random_state=42)
y_predict = kmeans.fit_predict(scaled_features)

In [21]:
kmeans.inertia_
kmeans.n_iter_

10

In [22]:
kmeans.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,

In [23]:
confusion_matrix(y, y_predict)


array([[ 93,  45],
       [ 12, 153]])

In [25]:
accuracy_score(y,y_predict)


0.8118811881188119